services:
  - type: web
    name: whatsapp-school-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ACCESS_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: GRAPH_API_VERSION
        value: v20.0
      - key: SCHOOL_IMAGE_URL
        sync: false
      - key: SERVICE_MENU_DELAY_SECONDS
        value: "3"
      - key: ADMISSION_FORM_PDF_URL
        sync: false
      - key: ONLINE_ADMISSION_FORM_URL
        value: https://pspublicschool.com
      - key: EXAM_BACKEND_STUDENT_LOGIN_URL
        sync: false
